apiVersion: v1
kind: Service
metadata:
  name: voting-pod-service
  labels:
    name: voting-pod-service
    app: example-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    tagetPort: 80
  selector:
    name: voting-app-pod
    app: example-voting-app